---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(action): "

  - package-ecosystem: "maven"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(mvn): "

  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(docker): "
