name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test ${{ matrix.quarkus_version }}
    strategy:
      fail-fast: false
      matrix:
        quarkus_version: [ "3.23.0", "3.23.1", "3.23.2" ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - uses: actions/checkout@v4
        with:
          repository: smallrye/smallrye-config
          path: smallrye-config

      - run: |
          mvn clean install -B -ntp -DskipTests -f smallrye-config/pom.xml

      - name: Verify
        run: |
          export RULESET_CUSTOMER_ORDER_EVENT_AND_CHANNELS_AT_0__CHANNELS=email,push
          ./mvnw clean verify -B -ntp -Dquarkus.platform.version=${{ matrix.quarkus_version }}

      - name: Publish Test Report
        if: ${{ failure() }}
        uses: scacap/action-surefire-report@v1
        with:
          fail_if_no_tests: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
