name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Verify
      run: ./mvnw -B -ntp clean verify

    - name: Publish Test Report
      if: ${{ failure() }}
      uses: scacap/action-surefire-report@v1
      with:
        fail_if_no_tests: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
