---
name: Dependabot CI
on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  build:
    name: Dependabot CI
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'beiertu-mms/quarkus-kotlin-playground'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Verify
        run: ./mvnw -B -ntp clean verify

      - name: Fetch PR metadata
        uses: dependabot/fetch-metadata@v2.2.0
        id: dependabot-metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
